name: Build

on:
  push:
    branches: ['main']

jobs:
  macos:
    name: >
      macOS
      ${{ matrix.osversion }}
    runs-on: macos-${{ matrix.osversion }}
    strategy:
      fail-fast: false
      matrix:
        osversion: ["12"] #, "11"
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: thisrepo
    - name: Checkout pkgsrc
      uses: actions/checkout@v4
      with:
        repository: NetBSD/pkgsrc
        path: pkgsrc-current
    - name: Build and Package
      run: |
        set -e

        # smush these files into pkgsrc
        cd thisrepo
        pkgdir=$(basename $(bmake show-var VARNAME=PKGDIR))
        category=$(grep CATEGORIES= Makefile | awk '{print $2}')
        cd ..
        rm -rf pkgsrc-current/${category}/${pkgdir}
        mv thisrepo pkgsrc-current/${category}/${pkgdir}

        # bootstrap pkgsrc (XXX cache this)
        cd pkgsrc-current/bootstrap
        sudo ./bootstrap --prefix /opt/pkg
        PATH=/opt/pkg/sbin:/opt/pkg/bin:$PATH

        # generate package
        cd ../${category}/${pkgdir}
        bmake package
        pkgfile=$(bmake show-var VARNAME=PKGFILE)
        ls -l ${pkgfile}
        pkg_info -L ${pkgfile}

        # publish release
        # XXX how?
