name: Build

on:
  push:
    branches: ['main']

jobs:
  macos:
    name: >
      macOS
      ${{ matrix.osversion }}
    runs-on: macos-${{ matrix.osversion }}
    strategy:
      fail-fast: false
      matrix:
        osversion: ["12"] #, "11"
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: this-schmonz-repo
    - name: Checkout pkgsrc
      uses: actions/checkout@v4
      with:
        repository: NetBSD/pkgsrc
        path: pkgsrc-current
    - name: Build and Package
      run: |
        set -e

        # bootstrap pkgsrc (XXX cache this)
        pushd pkgsrc-current/bootstrap
        sudo ./bootstrap --prefix /opt/pkg
        PATH=/opt/pkg/sbin:/opt/pkg/bin:$PATH
        popd

        # smush these files into pkgsrc
        category=$(grep CATEGORIES= this-schmonz-repo/Makefile | awk '{print $2}')
        mv this-schmonz-repo pkgsrc-current/${category}

        # generate package
        pushd pkgsrc-current/${category}/this-schmonz-repo
        bmake package
        pkgfile=$(bmake show-var VARNAME=PKGFILE)
        ls -l ${pkgfile}
        pkg_info -L ${pkgfile}

        # publish release
        # XXX how?
