name: VM

on:
  push:
    branches: ['main']

jobs:
  netbsd:
    name: >
      NetBSD
      ${{ matrix.osversion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        osversion: ["9.3"]
    steps:
    - name: Restore bootstrap
      id: bootstrap-restore
      uses: actions/cache/restore@v4
      with:
        path: /opt/pkg
        key: NetBSD-${{ matrix.osversion }}-bootstrap-${{ github.run_id }}
        restore-keys: NetBSD-${{ matrix.osversion }}-bootstrap-

    - name: Build bootstrap and packages
      id: bootstrap-build
      uses: vmactions/netbsd-vm@v1
      with:
        release: ${{ matrix.osversion }}
        usesh: true
        prepare: |
          pkg_add git-base
        run: |
          set -e

          # $HOME is /root
          # /root/work -> /home/runner/work
          # /home/runner/work looks reaaaaal empty though
          # where is everything from the host GITHUB_WORKSPACE?
          # host GITHUB_WORKSPACE = /home/runner/work/pkgsrc-mlog/pkgsrc-mlog
          # does actions/checkout affect the VM? notqmail's seems to

          # sh: cannot create /home/runner/work/_temp/_runner_file_commands/set_env_3bfecdc6-e85b-47d7-9bfc-f27cdd564145: directory nonexistent
          mkdir -p /home/runner/work/_temp/_runner_file_commands

          git clone --depth=1 https://github.com/NetBSD/pkgsrc .
          git clone --depth=1 https://github.com/schmonz/pkgsrc-mlog this-category/this-package

          if [ ! -d /opt/pkg ]; then
            unset PKG_PATH
            cd bootstrap
            ./bootstrap --prefix /opt/pkg
            ./cleanup
            cd ..
          fi
          PATH=/opt/pkg/sbin:/opt/pkg/bin:${PATH}
          cd this-category/this-package
          bmake package

          # XXX WTF is GITHUB_WORKSPACE inside the VM
          mkdir ${GITHUB_WORKSPACE}/release-contents

          release_version=$(bmake show-var VARNAME=PKGVERSION)

          mv $(bmake show-var VARNAME=PKGFILE) ${GITHUB_WORKSPACE}/release-contents
          cd ${GITHUB_WORKSPACE}/release-contents
          for i in *.tgz; do
            mv $i NetBSD-${{ matrix.osversion }}-unprivileged-$i
          done
          release_asset=$(echo *.tgz)

          echo "release_version=${release_version}" >> "${GITHUB_ENV}"
          echo "release_asset=${GITHUB_WORKSPACE}/release-contents/${release_asset}" >> "${GITHUB_ENV}"

    - name: Save bootstrap
      id: bootstrap-save
      uses: actions/cache/save@v4
      if: always()
      with:
        path: /opt/pkg
        key: ${{ steps.bootstrap-restore.outputs.cache-primary-key }}

    - name: Pretend to publish package
      run: |
        set -e
        echo "VERSION: version ${{ env.release_version }}"
        echo "FILE: ${{ env.release_asset }}"

    - name: Publish package
      uses: softprops/action-gh-release@v1
      if: false
      with:
        files: ${{ env.release_asset }}
        name: ${{ env.release_version }}
