name: VM

# TODO:
#
# raise vmactions issue for nonexistent ${GITHUB_ENV} parent directory
# raise vmactions issue for sshfs maybe not working on NetBSD? (try FreeBSD first)
# /opt/pkg for macOS, /usr/pkg for everything else, so the packages could conceivably match official packages
# NetBSD
# - 22m27s sans cached bootstrap
# - 22m48s WITH cached bootstrap?!?!
# XXX extract run: to shell script in the repo, pass it any ${{ thingies }} it needs

on:
  push:
    branches: [main]

jobs:
  xplatform-action:
    name: >
      cross-platform-actions
      ${{ matrix.os.uname }}
      ${{ matrix.os.version }}
      ${{ matrix.os.arch }}
    runs-on: ${{ matrix.os.host }}
    strategy:
      fail-fast: false
      matrix:
        os:
          #- uname: FreeBSD
          #  lname: freebsd
          #  arch: x86-64
          #  version: '13.2' # XXX list?
          #  host: macos-latest
          #  prep: |
          #    sudo pkg install -y git
          - uname: NetBSD
            lname: netbsd
            arch: x86-64
            version: '9.3'
            host: macos-latest
            prep: |
              sudo pkgin -y install mozilla-rootcerts git-base
              sudo /usr/pkg/sbin/mozilla-rootcerts install
          #- uname: OpenBSD
          #  lname: openbsd
          #  arch: arm64
          #  version: '7.4'
          #  host: ubuntu-latest
          #  prep: |
          #    sudo pkg_add git
    steps:
    - name: Restore bootstrap
      id: bootstrap-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/cached-${{ matrix.os.lname }}-${{ matrix.os.version }}-${{ matrix.os.arch }}-opt-pkg
        key: ${{ matrix.os.uname }}-${{ matrix.os.version }}-${{ matrix.os.arch }}-bootstrap-${{ github.run_id }}
        restore-keys: ${{ matrix.os.uname }}-${{ matrix.os.version }}-${{ matrix.os.arch }}-bootstrap-

    - name: Build bootstrap and packages
      id: bootstrap-build
      uses: cross-platform-actions/action@v0.22.0
      with:
        operating_system: ${{ matrix.os.lname }}
        version: ${{ matrix.os.version }}
        architecture: ${{ matrix.os.arch }}
        shell: sh
        run: |
          set -e
          echo "SCHMONZ 1: $(date)"
          ${{ matrix.os.prep }}
          echo "SCHMONZ 2: $(date)"
          # work around vmactions bug
          ### mkdir -p $(dirname ${GITHUB_ENV})
          # fetch pkgsrc + this package
          echo "SCHMONZ 3: $(date)"
          git clone --verbose --depth=1 ${GITHUB_SERVER_URL}/NetBSD/pkgsrc
          echo "SCHMONZ 4: $(date)"
          git clone --verbose --depth=1 ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} pkgsrc/${GITHUB_REPOSITORY}
          echo "SCHMONZ 5: $(date)"
          # bootstrap pkgsrc
          unset PKG_PATH
          if [ -d ${GITHUB_WORKSPACE}/cached-${{ matrix.os.lname }}-${{ matrix.os.version }}-${{ matrix.os.arch }}-opt-pkg ]; then
            sudo mkdir -p /opt
            sudo mv ${GITHUB_WORKSPACE}/cached-${{ matrix.os.lname }}-${{ matrix.os.version }}-${{ matrix.os.arch }}-opt-pkg /opt/pkg
          else
            cd pkgsrc/bootstrap
            sudo ./bootstrap --prefix /opt/pkg
            sudo ./cleanup
            cd ../..
          fi
          echo "SCHMONZ 6: $(date)"
          # build this package
          PATH=/opt/pkg/sbin:/opt/pkg/bin:${PATH}
          cd pkgsrc/${GITHUB_REPOSITORY}
          bmake SU_CMD="sudo ${SHELL} -c" package
          echo "SCHMONZ 7: $(date)"
          # XXX debug
          set -x
          # gather up artifacts
          release_version=$(bmake show-var VARNAME=PKGVERSION)
          echo "release_version=${release_version}" >> "${GITHUB_ENV}"
          mkdir ${GITHUB_WORKSPACE}/release-contents
          mv $(bmake show-var VARNAME=PKGFILE) ${GITHUB_WORKSPACE}/release-contents
          cd ${GITHUB_WORKSPACE}/release-contents
          for i in *.tgz; do mv $i cross-platform-actions-{{ matrix.os.lname }}-${{ matrix.os.version }}-${{ matrix.os.arch }}-$i; done
          release_asset=$(echo *.tgz)
          echo "release_asset=${GITHUB_WORKSPACE}/release-contents/${release_asset}" >> "${GITHUB_ENV}"
          echo "SCHMONZ 8: $(date)"
          # put bootstrap somewhere cacheable
          sudo mv /opt/pkg ${GITHUB_WORKSPACE}/cached-${{ matrix.os.lname }}-${{ matrix.os.version }}-${{ matrix.os.arch }}-opt-pkg
          echo "SCHMONZ 9: $(date)"
          # avoid unneeded big slow rsync
          rm -rf ${GITHUB_WORKSPACE}/pkgsrc
          echo "SCHMONZ 10: $(date)"

    - name: Save bootstrap
      id: bootstrap-save
      uses: actions/cache/save@v4
      if: always()
      with:
        path: ${{ github.workspace }}/cached-${{ matrix.os.lname }}-${{ matrix.os.version }}-${{ matrix.os.arch }}-opt-pkg
        key: ${{ steps.bootstrap-restore.outputs.cache-primary-key }}

    - name: Pretend to publish package
      run: |
        set -e
        echo "VERSION: version ${{ env.release_version }}"
        echo "FILE: ${{ env.release_asset }}"

  vm-action:
    name: >
      vmactions
      ${{ matrix.os.uname }}
      ${{ matrix.os.version }}
      ${{ matrix.os.arch }}
    runs-on: ${{ matrix.os.host }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - uname: NetBSD
            lname: netbsd
            arch: dummyarch
            version: '9.3'
            host: ubuntu-latest
            prep: |
              set -e
              /usr/sbin/pkg_add git-base
    steps:
    - name: Restore bootstrap
      id: bootstrap-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/cached-${{ matrix.os.lname }}-${{ matrix.os.version }}-${{ matrix.os.arch }}-opt-pkg
        key: ${{ matrix.os.uname }}-${{ matrix.os.version }}-${{ matrix.os.arch }}-bootstrap-${{ github.run_id }}
        restore-keys: ${{ matrix.os.uname }}-${{ matrix.os.version }}-${{ matrix.os.arch }}-bootstrap-

    - name: Build bootstrap and packages
      id: bootstrap-build
      uses: vmactions/netbsd-vm@v1
      with:
        release: ${{ matrix.os.version }}
        usesh: true
        prepare: |
          ${{ matrix.os.prep }}
        run: |
          set -e
          echo "SCHMONZ 1: $(date)"
          ### ${{ matrix.os.prep }}
          echo "SCHMONZ 2: $(date)"
          # work around vmactions bug
          mkdir -p $(dirname ${GITHUB_ENV})
          # fetch pkgsrc + this package
          echo "SCHMONZ 3: $(date)"
          git clone --verbose --depth=1 ${GITHUB_SERVER_URL}/NetBSD/pkgsrc
          echo "SCHMONZ 4: $(date)"
          git clone --verbose --depth=1 ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} pkgsrc/${GITHUB_REPOSITORY}
          echo "SCHMONZ 5: $(date)"
          # bootstrap pkgsrc
          unset PKG_PATH
          if [ -d ${GITHUB_WORKSPACE}/cached-${{ matrix.os.lname }}-${{ matrix.os.version }}-${{ matrix.os.arch }}-opt-pkg ]; then
            mkdir -p /opt
            mv ${GITHUB_WORKSPACE}/cached-${{ matrix.os.lname }}-${{ matrix.os.version }}-${{ matrix.os.arch }}-opt-pkg /opt/pkg
          else
            cd pkgsrc/bootstrap
            ./bootstrap --prefix /opt/pkg
            ./cleanup
            cd ../..
          fi
          echo "SCHMONZ 6: $(date)"
          # build this package
          PATH=/opt/pkg/sbin:/opt/pkg/bin:${PATH}
          cd pkgsrc/${GITHUB_REPOSITORY}
          bmake package
          echo "SCHMONZ 7: $(date)"
          # gather up artifacts
          release_version=$(bmake show-var VARNAME=PKGVERSION)
          echo "release_version=${release_version}" >> "${GITHUB_ENV}"
          mkdir ${GITHUB_WORKSPACE}/release-contents
          mv $(bmake show-var VARNAME=PKGFILE) ${GITHUB_WORKSPACE}/release-contents
          cd ${GITHUB_WORKSPACE}/release-contents
          for i in *.tgz; do mv $i vmactions-${{ matrix.os.lname }}-${{ matrix.os.version }}-${{ matrix.os.arch }}-$i; done
          release_asset=$(echo *.tgz)
          echo "release_asset=${GITHUB_WORKSPACE}/release-contents/${release_asset}" >> "${GITHUB_ENV}"
          echo "SCHMONZ 8: $(date)"
          # put bootstrap somewhere cacheable
          mv /opt/pkg ${GITHUB_WORKSPACE}/cached-${{ matrix.os.lname }}-${{ matrix.os.version }}-${{ matrix.os.arch }}-opt-pkg
          echo "SCHMONZ 9: $(date)"
          # avoid unneeded big slow rsync
          rm -rf ${GITHUB_WORKSPACE}/pkgsrc
          echo "SCHMONZ 10: $(date)"

    - name: Save bootstrap
      id: bootstrap-save
      uses: actions/cache/save@v4
      if: always()
      with:
        path: ${{ github.workspace }}/cached-${{ matrix.os.lname }}-${{ matrix.os.version }}-${{ matrix.os.arch }}-opt-pkg
        key: ${{ steps.bootstrap-restore.outputs.cache-primary-key }}

    - name: Pretend to publish package
      run: |
        set -e
        echo "VERSION: version ${{ env.release_version }}"
        echo "FILE: ${{ env.release_asset }}"

    - name: Publish package
      uses: softprops/action-gh-release@v1
      if: false
      with:
        files: ${{ env.release_asset }}
        name: ${{ env.release_version }}
