name: VM

# TODO:
#
# 1. Set bootstrap prefix to match available binary package repos,
#    or else the default for the platform
#    - mostly /usr/pkg (and /usr/pkg/pkgdb)
#    - macOS: /opt/pkg to avoid SIP and match pkgsrc.smartos.org
#    - SmartOS: what's the default in their repos?
#
# 2. Include compiler, prefix, and ABI in the publishable filenames
#    - And anything else my self-hosted VMs would cook into ${PACKAGES}
#
# 3. Add non-x86 BSD platforms via cross-platform-actions
#    - File an issue requesting NetBSD 10 aarch64
# 
# 4. Add Alpine builds for all available platforms
#
# 5. If branch == main, publish all the binary packages
#    - pkgsrc commit message with the changelog -> GitHub release notes
#    - borrow from <https://github.com/FWDekker/mommy/blob/dev/.github/workflows/cd.yml>
#
# 6. if sshfs can be reliable and fast on all platforms, clone pkgsrc only 1x (on the host)
#    - else try one more time to actions/cache pkgsrc on the host
#
# 7. Publish this as a GitHub Action!
#
# 8. Use it in all my package repos
#
# 9. Tell other pkgsrc developers about it

on:
  push:
    branches: [main]

jobs:
  build-all-packages:
    name: >
      ${{ matrix.os.uname }}
      ${{ matrix.os.arch }}
      ${{ matrix.os.version }}
    runs-on: ${{ matrix.os.host }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - uname: Alpine
            lname: alpine
            arch: x86_64
            version: 'edge'
            host: ubuntu-latest
            guest: jirutka/setup-alpine@v1
            prep: build-base check check-dev pkgconf

          - uname: Alpine
            lname: alpine
            arch: x86
            version: 'edge'
            host: ubuntu-latest
            guest: jirutka/setup-alpine@v1
            prep: build-base check check-dev pkgconf

          - uname: Alpine
            lname: alpine
            arch: armhf
            version: 'edge'
            host: ubuntu-latest
            guest: jirutka/setup-alpine@v1
            prep: build-base check check-dev pkgconf

          - uname: Alpine
            lname: alpine
            arch: armv7
            version: 'edge'
            host: ubuntu-latest
            guest: jirutka/setup-alpine@v1
            prep: build-base check check-dev pkgconf

          - uname: Alpine
            lname: alpine
            arch: aarch64
            version: 'edge'
            host: ubuntu-latest
            guest: jirutka/setup-alpine@v1
            prep: build-base check check-dev pkgconf

          - uname: Alpine
            lname: alpine
            arch: ppc64le
            version: 'edge'
            host: ubuntu-latest
            guest: jirutka/setup-alpine@v1
            prep: build-base check check-dev pkgconf

          - uname: Alpine
            lname: alpine
            arch: riscv64
            version: 'edge'
            host: ubuntu-latest
            guest: jirutka/setup-alpine@v1
            prep: build-base check check-dev pkgconf

          - uname: Alpine
            lname: alpine
            arch: s390x
            version: 'edge'
            host: ubuntu-latest
            guest: jirutka/setup-alpine@v1
            prep: build-base check check-dev pkgconf

          - uname: DragonFlyBSD
            lname: dragonflybsd
            arch: amd64
            version: '6.4.0'
            host: ubuntu-latest
            guest: vmactions/dragonflybsd-vm@v1
            prep: pkg upgrade -y; pkg install -y git

          - uname: FreeBSD
            lname: freebsd
            arch: amd64
            version: '14.0'
            host: ubuntu-latest
            guest: vmactions/freebsd-vm@v1
            prep: pkg install -y git

          - uname: macOS
            lname: macos
            arch: amd64
            version: 'latest'
            host: macos-latest
            guest: 
            prep: 

          - uname: NetBSD
            lname: netbsd
            arch: amd64
            version: '9.3'
            host: ubuntu-latest
            guest: vmactions/netbsd-vm@v1
            prep: /usr/sbin/pkg_add git-base

          - uname: OmniOS
            lname: omnios
            arch: amd64
            version: 'r151048'
            host: ubuntu-latest
            guest: vmactions/omnios-vm@v1
            prep: pkg install developer/versioning/git developer/gcc10 system/header developer/build/make

          - uname: OpenBSD
            lname: openbsd
            arch: amd64
            version: '7.4'
            host: ubuntu-latest
            guest: vmactions/openbsd-vm@v1
            prep: pkg_add git

          - uname: OpenBSD
            lname: openbsd
            arch: arm64
            version: '7.4'
            host: ubuntu-latest
            guest: cross-platform-actions/action@v0.22.0
            prep: sudo pkg_add git

          - uname: Solaris
            lname: solaris
            arch: amd64
            version: '11.4-gcc' # XXX include compiler in all package filenames, but not specially here
            host: ubuntu-latest
            guest: vmactions/solaris-vm@v1
            prep: pkgutil -y -i git

          - uname: Ubuntu
            lname: ubuntu
            arch: amd64
            version: 'latest'
            host: ubuntu-latest
            guest: 
            prep: 
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: move-under-pkgsrc-once-you-have-pkgsrc

    - name: Restore bootstrap
      id: bootstrap-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/cached-${{ matrix.os.lname }}-${{ matrix.os.arch }}-${{ matrix.os.version }}-opt-pkg
        key: ${{ matrix.os.lname }}-${{ matrix.os.arch }}-${{ matrix.os.version }}-bootstrap-${{ github.run_id }}
        restore-keys: ${{ matrix.os.lname }}-${{ matrix.os.arch }}-${{ matrix.os.version }}-bootstrap-

    - name: Build (alpine setup)
      if: ${{ startsWith(matrix.os.guest, 'jirutka/') }}
      id: bootstrap-build-alpine-setup
      uses: jirutka/setup-alpine@v1
      with:
        branch: ${{ matrix.os.version }}
        arch: ${{ matrix.os.arch }}
        packages: ${{ matrix.os.prep }}
    - name: Build (alpine)
      if: ${{ startsWith(matrix.os.guest, 'jirutka/') }}
      id: bootstrap-build-alpine
      shell: alpine.sh --root {0}
      run: |
        set -e; git clone --verbose --depth=1 ${GITHUB_SERVER_URL}/NetBSD/pkgsrc; mkdir -p pkgsrc/schmonz; mv move-under-pkgsrc-once-you-have-pkgsrc pkgsrc/${GITHUB_REPOSITORY}; ./pkgsrc/${GITHUB_REPOSITORY}/.github/workflows/bootstrap-and-build.sh ${{ matrix.os.lname }} ${{ matrix.os.arch }} ${{ matrix.os.version }}

    - name: Build (cross-platform-actions)
      if: ${{ false && startsWith(matrix.os.guest, 'cross-platform-actions/') }}
      id: bootstrap-build-cross-platform-actions
      uses: jenseng/dynamic-uses@v1
      with:
        uses: ${{ matrix.os.guest }}
        with: |
          {
            "operating_system": "${{ matrix.os.lname }}",
            "architecture": "${{ matrix.os.arch }}",
            "version": "${{ matrix.os.version }}",
            "shell": "sh",
            "run": "set -e; ${{ matrix.os.prep }}; git clone --verbose --depth=1 ${GITHUB_SERVER_URL}/NetBSD/pkgsrc; mkdir -p pkgsrc/schmonz; mv move-under-pkgsrc-once-you-have-pkgsrc pkgsrc/${GITHUB_REPOSITORY}; sudo env GITHUB_REPOSITORY=${GITHUB_REPOSITORY} GITHUB_ENV=${GITHUB_ENV} ./pkgsrc/${GITHUB_REPOSITORY}/.github/workflows/bootstrap-and-build.sh ${{ matrix.os.lname }} ${{ matrix.os.arch }} ${{ matrix.os.version }}"
          }

    - name: Build (vmactions)
      if: ${{ false && startsWith(matrix.os.guest, 'vmactions/') }}
      id: bootstrap-build-vmactions
      uses: jenseng/dynamic-uses@v1
      with:
        uses: ${{ matrix.os.guest }}
        with: |
          {
            "release": "${{ matrix.os.version }}",
            "usesh": true,
            "sync": "rsync",
            "prepare": "set -e; ${{ matrix.os.prep }}",
            "run": "set -e; mkdir -p $(dirname ${GITHUB_ENV}); git clone --verbose --depth=1 ${GITHUB_SERVER_URL}/NetBSD/pkgsrc; mkdir -p pkgsrc/schmonz; mv move-under-pkgsrc-once-you-have-pkgsrc pkgsrc/${GITHUB_REPOSITORY}; ./pkgsrc/${GITHUB_REPOSITORY}/.github/workflows/bootstrap-and-build.sh ${{ matrix.os.lname }} ${{ matrix.os.arch }} ${{ matrix.os.version }}"
          }

    - name: Build (native)
      if: ${{ false && ! startsWith(matrix.os.guest, 'vmactions/') && ! startsWith(matrix.os.guest, 'cross-platform-actions/') }}
      id: bootstrap-build-native
      run:
        set -e; ${{ matrix.os.prep }}
        set -e; git clone --verbose --depth=1 ${GITHUB_SERVER_URL}/NetBSD/pkgsrc; mkdir -p pkgsrc/schmonz; mv move-under-pkgsrc-once-you-have-pkgsrc pkgsrc/${GITHUB_REPOSITORY}; sudo env GITHUB_REPOSITORY=${GITHUB_REPOSITORY} GITHUB_ENV=${GITHUB_ENV} ./pkgsrc/${GITHUB_REPOSITORY}/.github/workflows/bootstrap-and-build.sh ${{ matrix.os.lname }} ${{ matrix.os.arch }} ${{ matrix.os.version }}

    - name: Save bootstrap
      id: bootstrap-save
      uses: actions/cache/save@v4
      if: always()
      with:
        path: ${{ github.workspace }}/cached-${{ matrix.os.lname }}-${{ matrix.os.arch }}-${{ matrix.os.version }}-opt-pkg
        key: ${{ steps.bootstrap-restore.outputs.cache-primary-key }}

    - name: Pretend to publish package
      run: |
        set -e
        echo "VERSION: version ${{ env.release_version }}"
        echo "FILE: ${{ env.release_asset }}"

